version: '2'
services:
    web:
        image: httpd:2.4
        container_name: "uea-admin"
        restart: always
        volumes:
            - ../:/usr/local/apache2/htdocs/
        ports:
          - 8002:80
